version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: /operator
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 10
