//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Written manually — controller-gen is not available in this environment.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumHub) DeepCopyInto(out *ScutumHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ScutumHub.
func (in *ScutumHub) DeepCopy() *ScutumHub {
	if in == nil {
		return nil
	}
	out := new(ScutumHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ScutumHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumHubList) DeepCopyInto(out *ScutumHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScutumHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ScutumHubList.
func (in *ScutumHubList) DeepCopy() *ScutumHubList {
	if in == nil {
		return nil
	}
	out := new(ScutumHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ScutumHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumHubSpec) DeepCopyInto(out *ScutumHubSpec) {
	*out = *in
	if in.Replicas != nil {
		x := *in.Replicas
		out.Replicas = &x
	}
	out.Database = in.Database
	out.TLS = in.TLS
	out.WireGuard = in.WireGuard
	out.Storage = in.Storage
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy creates a deep copy of ScutumHubSpec.
func (in *ScutumHubSpec) DeepCopy() *ScutumHubSpec {
	if in == nil {
		return nil
	}
	out := new(ScutumHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumHubDatabase) DeepCopyInto(out *ScutumHubDatabase) {
	*out = *in
}

// DeepCopy creates a deep copy of ScutumHubDatabase.
func (in *ScutumHubDatabase) DeepCopy() *ScutumHubDatabase {
	if in == nil {
		return nil
	}
	out := new(ScutumHubDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumHubTLS) DeepCopyInto(out *ScutumHubTLS) {
	*out = *in
}

// DeepCopy creates a deep copy of ScutumHubTLS.
func (in *ScutumHubTLS) DeepCopy() *ScutumHubTLS {
	if in == nil {
		return nil
	}
	out := new(ScutumHubTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumHubWireGuard) DeepCopyInto(out *ScutumHubWireGuard) {
	*out = *in
}

// DeepCopy creates a deep copy of ScutumHubWireGuard.
func (in *ScutumHubWireGuard) DeepCopy() *ScutumHubWireGuard {
	if in == nil {
		return nil
	}
	out := new(ScutumHubWireGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumHubStorage) DeepCopyInto(out *ScutumHubStorage) {
	*out = *in
}

// DeepCopy creates a deep copy of ScutumHubStorage.
func (in *ScutumHubStorage) DeepCopy() *ScutumHubStorage {
	if in == nil {
		return nil
	}
	out := new(ScutumHubStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumHubStatus) DeepCopyInto(out *ScutumHubStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ScutumHubStatus.
func (in *ScutumHubStatus) DeepCopy() *ScutumHubStatus {
	if in == nil {
		return nil
	}
	out := new(ScutumHubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumNode) DeepCopyInto(out *ScutumNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ScutumNode.
func (in *ScutumNode) DeepCopy() *ScutumNode {
	if in == nil {
		return nil
	}
	out := new(ScutumNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ScutumNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumNodeList) DeepCopyInto(out *ScutumNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScutumNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ScutumNodeList.
func (in *ScutumNodeList) DeepCopy() *ScutumNodeList {
	if in == nil {
		return nil
	}
	out := new(ScutumNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ScutumNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumNodeSpec) DeepCopyInto(out *ScutumNodeSpec) {
	*out = *in
	out.HubRef = in.HubRef
	out.Storage = in.Storage
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy creates a deep copy of ScutumNodeSpec.
func (in *ScutumNodeSpec) DeepCopy() *ScutumNodeSpec {
	if in == nil {
		return nil
	}
	out := new(ScutumNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumNodeStorage) DeepCopyInto(out *ScutumNodeStorage) {
	*out = *in
}

// DeepCopy creates a deep copy of ScutumNodeStorage.
func (in *ScutumNodeStorage) DeepCopy() *ScutumNodeStorage {
	if in == nil {
		return nil
	}
	out := new(ScutumNodeStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ScutumNodeStatus) DeepCopyInto(out *ScutumNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ScutumNodeStatus.
func (in *ScutumNodeStatus) DeepCopy() *ScutumNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ScutumNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// Ensure corev1 is used (LocalObjectReference is referenced in ScutumNodeSpec).
var _ corev1.LocalObjectReference
