// Generates an M3 (Material Design 3) color token set from the real Scutum
// brand colors (logo blue as primary seed, logo green as secondary seed) and
// writes them as CSS custom properties to src/theme.css.
//
// Re-run with `npm run theme:gen` whenever the seed colors change.
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import {
  argbFromHex,
  hexFromArgb,
  Hct,
  TonalPalette,
  DynamicScheme,
  Variant,
} from '@material/material-color-utilities'

const PRIMARY_SEED = '#0E7AAF' // Scutum shield blue
const SECONDARY_SEED = '#6FC2A0' // Scutum shield green

const sourceHct = Hct.fromInt(argbFromHex(PRIMARY_SEED))
const secondaryHct = Hct.fromInt(argbFromHex(SECONDARY_SEED))
const secondaryPalette = TonalPalette.fromHueAndChroma(secondaryHct.hue, secondaryHct.chroma)

// Role -> DynamicScheme getter name. Covers the full M3 surface/color role set.
const ROLES = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'inversePrimary',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'background', 'onBackground',
  'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant',
  'surfaceDim', 'surfaceBright',
  'surfaceContainerLowest', 'surfaceContainerLow', 'surfaceContainer',
  'surfaceContainerHigh', 'surfaceContainerHighest',
  'outline', 'outlineVariant', 'shadow', 'scrim',
  'inverseSurface', 'inverseOnSurface', 'surfaceTint',
]

function buildScheme(isDark) {
  return new DynamicScheme({
    sourceColorHct: sourceHct,
    variant: Variant.TONAL_SPOT,
    contrastLevel: 0,
    isDark,
    secondaryPalette,
  })
}

// camelCase -> kebab-case, e.g. onPrimaryContainer -> on-primary-container
const toKebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

function cssBlock(scheme) {
  return ROLES.map((role) => `  --md-${toKebab(role)}: ${hexFromArgb(scheme[role])};`).join('\n')
}

const dark = buildScheme(true)
const light = buildScheme(false)

const css = `/* AUTO-GENERATED by scripts/generate-theme.mjs — do not hand-edit.
   Seeded from the real Scutum brand mark: primary ${PRIMARY_SEED} (logo blue),
   secondary ${SECONDARY_SEED} (logo green). Tertiary/neutral/error are
   algorithmically derived by the M3 Tonal Spot variant. Re-run:
   npm run theme:gen */

:root {
${cssBlock(dark)}
}

[data-theme='light'] {
${cssBlock(light)}
}
`

const outPath = fileURLToPath(new URL('../src/theme.css', import.meta.url))
writeFileSync(outPath, css)
console.log(`Wrote ${outPath}`)
