#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_ROOT/cmd/internal/utils"
BINARY_PATH="$OUTPUT_DIR/wg_binary.go"
TMP_DIR=$(mktemp -d)

cleanup() {
    rm -rf "$TMP_DIR"
}
trap cleanup EXIT

echo "=== Building static wg binary ==="

cd "$TMP_DIR"

echo "Cloning wireguard-tools..."
git clone --depth 1 https://github.com/WireGuard/wireguard-tools.git

cd wireguard-tools/src

echo "Building static wg..."
make CGO_ENABLED=0 LDFLAGS="-s -w -static" wg

echo "Checking binary is static..."
file wg || true
ldd wg 2>&1 || echo "No dynamic linking (good)"

echo "Converting to Go embeddable format..."

# Copy binary directly - go:embed can handle it
cp wg "$OUTPUT_DIR/wg-embedded"

# Create marker file
cat > "$OUTPUT_DIR/wg_binary.go" << EOF
// Code generated by build-embedded-wg.sh. DO NOT EDIT.
//go:embed wg-embedded
var EmbeddedWgBinary []byte
EOF

echo "Binary size: $(stat -c%s wg) bytes"

echo ""
echo "=== Successfully created $BINARY_PATH ==="
echo "Binary size: $(stat -c%s wg) bytes"